package com.p000;

import java.util.concurrent.TimeUnit;
import p000.anq.C0650a;

/* renamed from: asl */
public final class asl<R extends ant> extends anp<R> {
    /* renamed from: a */
    private final ark<R> f4255a;

    public asl(anq<R> anq) {
        if (anq instanceof ark) {
            this.f4255a = (ark) anq;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    /* renamed from: a */
    public R m5487a(long j, TimeUnit timeUnit) {
        return this.f4255a.m2678a(j, timeUnit);
    }

    /* renamed from: a */
    public void mo345a(C0650a c0650a) {
        this.f4255a.mo345a(c0650a);
    }

    /* renamed from: a */
    public void mo346a(anu<? super R> anu) {
        this.f4255a.mo346a((anu) anu);
    }

    /* renamed from: a */
    public boolean mo708a() {
        return this.f4255a.m2686d();
    }

    /* renamed from: b */
    public R mo709b() {
        if (mo708a()) {
            return m5487a(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    /* renamed from: c */
    public Integer mo347c() {
        return this.f4255a.mo347c();
    }
}
