package com.p000;

import com.google.android.gms.common.api.Status;
import p000.anq.C0650a;

/* renamed from: asq */
public class asq<R extends ant> extends anq<R> {
    /* renamed from: a */
    private final Status f4262a;

    /* renamed from: a */
    Status m5495a() {
        return this.f4262a;
    }

    /* renamed from: a */
    public void mo345a(C0650a c0650a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public void mo346a(anu<? super R> anu) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public Integer mo347c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
